### PR TITLE
use a fount to model incoming connections

### LINKED ISSUE #27: replace conversion of flow-function → factory with conversion of endpoint → fount of founts
Presently on trunk, tubes are hooked up to the outside world (i.e.: Twisted) by converting a "flow function", a function taking a fount and drain, to a Factory, which is then hooked up to Twisted.

However, this is limiting in one major regard: the backpressure of *not accepting future connections* is impossible to model properly.

A better way to conceptualize a listening socket is a fount whose `outputType` is an object with both `Fount` and `Drain` attributes.  This way, we can flow the stream of incoming connections to a "listening" drain, which can exert backpressure (most obviously by simply limiting the number of concurrently active connections).

As it happens, this is also a feature missing from Twisted which makes it hard to implement fairness in queueing.  By making tubes treat listening sockets and connected sockets consistently, we can open up a whole new area of correct-by-default behavior under high levels of load.

### PR DESCRIPTION
**Pull request by glyph**
Fix #27

[Review on Reviewable](https://reviewable.io/reviews/twisted/tubes/26)

### CODE REVIEW

**Comment by glyph** [comment]
Hey @mithrandi - If you can't review this in the next couple of days I'll probably just self-review it and land since I don't think anyone is looking at the tubes review queue.  Unless @david415 would like to have a look?

**Comment by david415** [comment]
doh... reviewable.io doesn't work for me because "Github request quota".

**Comment by glyph** [comment]
@david415 - thanks for having a look!  Would you mind checking again?  I'm going to go out on a limb and assume that was a temporary outage.  If not, we may have to disable the check...

**Comment by glyph** [comment]
Reviewed 10 of 14 files at r1, 3 of 4 files at r2, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

_[docs/listings/portforward.py, line 1 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YsuWk0ldRHI5JhyDr:-K3YsuWk0ldRHI5JhyDs:-652609575) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/docs/listings/portforward.py#L1)):_
Running this example now yields a traceback:

Unhandled Error
Traceback (most recent call last):
  File "/Users/glyph/.virtualenvs/Tubes/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/glyph/.virtualenvs/Tubes/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/glyph/.virtualenvs/Tubes/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/glyph/.virtualenvs/Tubes/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/glyph/.virtualenvs/Tubes/lib/python2.7/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Users/glyph/.virtualenvs/Tubes/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/Users/glyph/.virtualenvs/Tubes/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/glyph/Projects/Tubes/tubes/protocol.py", line 254, in dataReceived
    drain.receive(data)
  File "/Users/glyph/Projects/Tubes/tubes/_siphon.py", line 326, in receive
    self._siphon._deliverFrom(tubeReceivedItem)
  File "/Users/glyph/Projects/Tubes/tubes/_siphon.py", line 439, in _deliverFrom
    self._unbufferIterator()
  File "/Users/glyph/Projects/Tubes/tubes/_siphon.py", line 463, in _unbufferIterator
    self._tfount.drain.receive(value)
exceptions.AttributeError: 'Flow' object has no attribute 'receive'

---

_[docs/listings/reversetube.py, line 1 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3Yt5wvnsoAIuDhexgF:-K3Yt5wvnsoAIuDhexgG:-282095980) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/docs/listings/reversetube.py#L1)):_
This now produces a traceback as well. Truncated, because StandardIO makes that happen >:-(

main function encountered error
Traceback (most recent call last):
  File "/Users/glyph/.virtualenvs/Tubes/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "docs/listings/reversetube.py", line 21, in main
    flowFount = yield flowFountFromEndpoint(endpoint)
  File "/Users/glyph/Projects/Tubes/tubes/protocol.py", line 388, in flowFountFromEndpoint
    return endpoint.listen(aFactory).addCallback(listening)
  File "/Users/glyph/.virtualenvs/Tubes/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 261, in listen
    reactor=self._reactor)
--- <exception caught here> ---
  File "/Users/glyph/.virtualenvs/Tubes/lib/python2.7/site-packages/twisted/internet/defer.py", line 121, in execute
    result = callable(*args, **kw)
  File "/Users/glyph/.virtualenvs/Tubes/lib/python2.7/site-packages/twisted/internet/_posixstdio.py", line 42, in __init__
    self.protocol.makeConnection(self)
  File "/Users/glyph/.virtualenvs

---

_[docs/listings/rpn.py, line 1 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YtJ4oCjyHyohkF7v_:-K3YtJ4oCjyHyohkF7va:1049972694) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/docs/listings/rpn.py#L1)):_
Same traceback as above.

---

_[tubes/listening.py, line 65 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YtUkoYdKusinCpn4V:-K3YtUkoYdKusinCpn4W:-1562490056) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/listening.py#L65)):_
This docstring needs filling out.

---

_[tubes/listening.py, line 67 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YtWMHpLNvhe0exPWa:-K3YtWMHpLNvhe0exPWb:1025148404) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/listening.py#L67)):_
This param needs filling out.

---

_[tubes/listening.py, line 69 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YtYFmtgXgiQd_EMCq:-K3YtYFmtgXgiQd_EMCr:2080079223) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/listening.py#L69)):_
Returning None is probably the right thing here but it should be explicit; this is a terminal drain.

---

_[tubes/protocol.py, line 310 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3Yu92qrwUlZvxf_H-f:-K3Yu92qrwUlZvxf_H-g:-485337115) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/protocol.py#L310)):_
Need @param for portObject

---

_[tubes/protocol.py, line 310 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YuCWVSOETs0hSXPoP:-K3YuCWVSOETs0hSXPoQ:-1576953592) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/protocol.py#L310)):_
Need @param for aFlowFunction

---

_[tubes/protocol.py, line 333 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YuKMxCkTYV9W61x1G:-K3YuKMxCkTYV9W61x1H:1037671655) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/protocol.py#L333)):_
This loop might not be reentrant. Possibly not a problem, but worth noting.  What can't aFlowFunction do?

---

_[tubes/protocol.py, line 340 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YuQlSVb2HGhWiABHy:-K3YuQlSVb2HGhWiABHz:-955264134) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/protocol.py#L340)):_
This could really be better.

---

_[tubes/protocol.py, line 349 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YuSKDRn8zM-5aTu3D:-K3YuSKELTTxq3E--_aa:1277026699) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/protocol.py#L349)):_
Same here; better docstring.

---

_[tubes/test/test_listening.py, line 19 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YuWeyW67wgoPijkl4:-K3YuWeyW67wgoPijkl5:-1730637650) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/test/test_listening.py#L19)):_
This is sorta like FakeDrain.  Either this should be in test.util or it should be deleted in favor of FakeDrain.

---

_[tubes/test/test_listening.py, line 50 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3Yuf9B-no8Vl5ANaxS:-K3Yuf9B-no8Vl5ANaxT:-167948765) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/test/test_listening.py#L50)):_
capital letter

---

_[tubes/test/test_listening.py, line 53 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YugcPjck4_AXYpn7z:-K3YugcPjck4_AXYpn8-:-274274514) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/test/test_listening.py#L53)):_
this should remember that it stopped

---

_[tubes/test/test_protocol.py, line 81 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3Yur4f9zOpIyf-M4rT:-K3Yur4f9zOpIyf-M4rU:-1025776066) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/test/test_protocol.py#L81)):_
Explain what "the adapted protocol" is a bit better here.

---

_[tubes/test/test_protocol.py, line 307 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3Yv63xePyToIm36yBh:-K3Yv63xePyToIm36yBi:1914704000) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/test/test_protocol.py#L307)):_
Should provide IPushProducer.

---

_[tubes/test/test_protocol.py, line 308 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YuwMd9GQXTfeBtLxD:-K3YuwMd9GQXTfeBtLxE:-1985780381) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/test/test_protocol.py#L308)):_
Maybe put in test.util so we can make a better habit of centralizing fakes.

---

_[tubes/test/test_protocol.py, line 313 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3Yv1j419m7qaN5xLhy:-K3Yv1j419m7qaN5xLhz:-1200505958) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/test/test_protocol.py#L313)):_
Except... they are part of a formal interface, IPushProducer, which this should also provide.

---

_[tubes/test/test_protocol.py, line 366 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3Yv7WQdajdpW1YsHQd:-K3Yv7WQdajdpW1YsHQe:1782787290) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/test/test_protocol.py#L366)):_
Should have a verifyClass about the interfaces provided above.

---

_[tubes/test/test_protocol.py, line 369 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YvAVBv_bMJZCor6QT:-K3YvAVBv_bMJZCor6QU:-1505984298) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/test/test_protocol.py#L369)):_
Should be in test.util.

---

_[tubes/test/test_protocol.py, line 380 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YvC4eA31n79egbA9_:-K3YvC4eA31n79egbA9a:2126289535) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/test/test_protocol.py#L380)):_
These attributes should be public on a separate object used to drive this externally.  As we have learned over and over again, we should separate our fakes from our inspectors.  https://glyph.twistedmatrix.com/2015/05/separate-your-fakes-and-your-inspectors.html

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/twisted/tubes/26)_

**Comment by glyph** [comment]
Reviewed 1 of 1 files at r6, 2 of 2 files at r7, 2 of 5 files at r8.
Review status: 14 of 17 files reviewed at latest revision, 14 unresolved discussions.

---

_[tubes/protocol.py, line 308 \[r6\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3Zq-NIEfFYLti2ZZD2:-K3Zq-NIEfFYLti2ZZD3:1824448764) ([raw file](https://github.com/twisted/tubes/blob/9e8ed344c6f823cd918ded7d22fb307068fa8322/tubes/protocol.py#L308)):_
need a @ param for preListen

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/twisted/tubes/26)_

**Comment by glyph** [comment]
Review status: 14 of 17 files reviewed at latest revision, 13 unresolved discussions.

---

_[tubes/protocol.py, line 333 \[r5\]](https://reviewable.io:443/reviews/twisted/tubes/26#-K3YuKMxCkTYV9W61x1G:-K3ZrSexmuuNjtXLifMM:-855315823) ([raw file](https://github.com/twisted/tubes/blob/e4ca94a51bbee2a086145b8d57769ea6178d8291/tubes/protocol.py#L333)):_
I know that aFlowFunction just constructs founts, so it's fine.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/twisted/tubes/26)_

**Comment by glyph** [comment]
Reviewed 1 of 5 files at r8, 2 of 2 files at r9, 2 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/twisted/tubes/26)_

**Comment by glyph** [comment]
Reviewed 3 of 3 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/twisted/tubes/26)_

**Comment by glyph** [comment]
When we have more contributors, I will stop doing self-reviews, but:

- i was surprised how thorough my self-review was, reviewable is great
- there is almost nobody watching this review queue
- 0.0.0 version number is not a joke, yoloooooo

**Comment by david415** [comment]
reviewable.io blocks tor exits. =-(

**Comment by glyph** [comment]
@david415 That's a bummer. Is this a dealbreaker for you? I'd really like to make both Tubes and eventually Twisted use reviewable, as it really relieves a lot of the work for more complex review workflows and larger changes…

**Comment by david415** [comment]
i suppose it's not a deal breaker... but rather inconvenient.
anyhow i found a bug: https://github.com/twisted/tubes/issues/33

**Comment by glyph** [comment]
@david415 glad to know it's not a dealbreaker for you. but let's get in touch with reviewable's support and see if there's anything they can do...

**Pull request merged**
