### PR TITLE
Unbreak pypi badge

### PR DESCRIPTION
**Pull request by ashfall**

### CODE REVIEW

**Comment by cristobal23** [comment]
This change looks fine. I will re-run the build.

**Comment by cristobal23** [comment]
I replicated the error in the invocation of pydoctor locally.  Some further investigation is necessary.

**Comment by ashfall** [comment]
Hm. Thanks for taking a look, I'll try to dig into this next week.

**Comment by glyph** [comment]
@ashfall - "next week", huh? :)

**Comment by ashfall** [comment]
Uh oh, thanks a lot for seeing this through!

**Pull request merged**
